CREATE OR REPLACE TABLE FUNCTION `tom-moretti.nameless_analytics.ec_products`(start_date DATE, end_date DATE) AS (
  with base_events as (
    select 
      # USER DATA
      user_date, 
      user_id,
      client_id, 
      user_type, 
      new_user, 
      returning_user,
      user_channel_grouping, 
      user_source,
      user_tld_source, 
      user_campaign, 
      user_campaign_id,
      user_campaign_click_id,
      user_campaign_term,
      user_campaign_content,
      user_device_type, 
      user_country, 
      user_language, 

      # SESSION DATA
      session_date, 
      session_id, 
      session_number, 
      cross_domain_session, 
      session_start_timestamp, 
      session_end_timestamp,
      session_duration_sec,
      new_session,
      returning_session,
      session_channel_grouping, 
      session_source,
      session_tld_source, 
      session_campaign,
      session_campaign_id,
      session_campaign_click_id,
      session_campaign_term,
      session_campaign_content,
      session_device_type, 
      session_browser_name,
      session_country, 
      session_language,
      session_hostname,

      # EVENT DATA
      event_date,
      event_timestamp,
      event_name,
      ecommerce
    from `tom-moretti.nameless_analytics.events`(start_date, end_date, 'session')
    where regexp_contains(event_name, 'view_promotion|select_promotion|view_item_list|select_item|view_item|add_to_wishlist|add_to_cart|remove_from_cart|view_cart|begin_checkout|add_shipping_info|add_payment_info|purchase|refund')
  ),

  product_logic as (
    select
      # USER DATA
      user_date,
      client_id,
      user_id,
      user_channel_grouping,
      split(user_tld_source, '.')[safe_offset(0)] as user_source_split,
      user_tld_source,
      user_campaign,
      user_device_type,
      user_country,
      user_language,
      user_type,
      new_user,
      returning_user,

      # SESSION DATA
      session_number,
      session_id,
      session_start_timestamp,
      session_channel_grouping,
      split(session_tld_source, '.')[safe_offset(0)] as session_source_split,
      session_tld_source,
      session_campaign,
      cross_domain_session,
      session_device_type,
      session_country,
      session_browser_name,
      session_language,

      # EVENT DATA
      event_date,
      event_name,
      timestamp_millis(event_timestamp) as event_datetime,

      # ECOMMERCE DATA
      json_value(ecommerce, '$.transaction_id') as transaction_id,
      json_value(ecommerce, '$.item_list_id') as list_id,
      json_value(ecommerce, '$.item_list_name') as list_name,
      json_value(ecommerce, '$.creative_name') as creative_name,
      json_value(ecommerce, '$.creative_slot') as creative_slot,
      json_value(ecommerce, '$.promotion_id') as promotion_id,
      json_value(ecommerce, '$.promotion_name') as promotion_name,

      json_value(items, '$.item_list_id') as item_list_id,
      json_value(items, '$.item_list_name') as item_list_name,
      json_value(items, '$.affiliation') as item_affiliation,
      json_value(items, '$.coupon') as item_coupon,
      safe_cast(json_value(items, '$.discount') as float64) as item_discount,
      json_value(items, '$.item_brand') as item_brand,
      json_value(items, '$.item_id') as item_id,
      json_value(items, '$.item_name') as item_name,
      json_value(items, '$.item_variant') as item_variant,
      json_value(items, '$.item_category') as item_category,
      json_value(items, '$.item_category2') as item_category_2,
      json_value(items, '$.item_category3') as item_category_3,
      json_value(items, '$.item_category4') as item_category_4,
      json_value(items, '$.item_category5') as item_category_5,
      safe_cast(json_value(items, '$.price') as float64) as item_price,
      
      case when event_name = 'purchase' then safe_cast(json_value(items, '$.quantity') as int64) end as item_quantity_purchased,
      case when event_name = 'refund' then safe_cast(json_value(items, '$.quantity') as int64) end as item_quantity_refunded,
      case when event_name = 'add_to_cart' then safe_cast(json_value(items, '$.quantity') as int64) end as item_quantity_added_to_cart,
      case when event_name = 'remove_from_cart' then safe_cast(json_value(items, '$.quantity') as int64) end as item_quantity_removed_from_cart,
      
      case when event_name = 'purchase' then safe_cast(json_value(items, '$.price') as float64) * safe_cast(json_value(items, '$.quantity') as int64) end as item_revenue_purchased,
      case when event_name = 'refund' then -safe_cast(json_value(items, '$.price') as float64) * safe_cast(json_value(items, '$.quantity') as int64) end as item_revenue_refunded,
      case when event_name = 'purchase' then 1 end as purchase_item_flag

    from base_events
    left join unnest(json_extract_array(ecommerce, '$.items')) as items
  ),

  product_prep as (
    select
      # USER DATA
      user_date, 
      client_id, 
      user_id, 
      user_channel_grouping, 
      user_source_split, 
      user_tld_source, 
      user_campaign, 
      user_device_type, 
      user_country, 
      user_language, 
      user_type, 
      new_user, 
      returning_user,
      
      # SESSION DATA
      session_number, 
      session_id, 
      session_start_timestamp, 
      session_channel_grouping, 
      session_source_split, 
      session_tld_source, 
      session_campaign, 
      cross_domain_session, 
      session_device_type, 
      session_country, 
      session_browser_name, 
      session_language,
      
      # EVENT DATA
      event_date, 
      event_name, 
      event_datetime,
      
      # ECOMMERCE DATA
      transaction_id, 
      list_id, 
      list_name, 
      item_list_id, 
      item_list_name, 
      item_affiliation, 
      item_coupon, 
      item_discount, 
      creative_name, 
      creative_slot, 
      promotion_id, 
      promotion_name, 
      item_brand, 
      item_id, 
      item_name, 
      item_variant, 
      item_category, 
      item_category_2, 
      item_category_3, 
      item_category_4, 
      item_category_5,
      
      countif(event_name = "view_promotion") as view_promotion,
      countif(event_name = "select_promotion") as select_promotion,
      countif(event_name = "view_item_list") as view_item_list,
      countif(event_name = "select_item") as select_item,
      countif(event_name = "view_item") as view_item,
      countif(event_name = "add_to_wishlist") as add_to_wishlist,
      countif(event_name = "add_to_cart") as add_to_cart,
      countif(event_name = "remove_from_cart") as remove_from_cart,
      countif(event_name = "view_cart") as view_cart,
      countif(event_name = "begin_checkout") as begin_checkout,
      countif(event_name = "add_shipping_info") as add_shipping_info,
      countif(event_name = "add_payment_info") as add_payment_info,

      sum(item_quantity_purchased) as item_quantity_purchased,
      sum(item_quantity_refunded) as item_quantity_refunded,
      sum(item_quantity_added_to_cart) as item_quantity_added_to_cart,
      sum(item_quantity_removed_from_cart) as item_quantity_removed_from_cart,
      sum(item_revenue_purchased) as item_purchase_revenue,
      sum(item_revenue_refunded) as item_refund_revenue,
      count(distinct case when purchase_item_flag = 1 then item_name end) as item_unique_purchases
    from product_logic
    group by all
  )

  select
    # USER DATA
    user_date,
    client_id,
    user_id,
    user_channel_grouping,
    user_source_split as user_source,
    user_tld_source,
    user_campaign,
    user_device_type,
    user_country,
    user_language,
    user_type,
    new_user,
    returning_user,

    # SESSION DATA
    session_number,
    session_id,
    session_start_timestamp,
    session_channel_grouping,
    session_source_split as session_source,
    session_tld_source,
    session_campaign,
    cross_domain_session,
    session_device_type,
    session_country,
    session_language,
    session_browser_name,
    
    # EVENT DATA
    event_date,
    event_name,
    event_datetime as event_timestamp,

    # ECOMMERCE DATA
    transaction_id, 
    list_id,
    list_name,
    item_list_id,
    item_list_name,
    item_affiliation,
    item_coupon,
    item_discount,
    creative_name,
    creative_slot,
    promotion_id,
    promotion_name,
    item_brand,
    item_id,
    item_name,
    item_variant,
    item_category,
    item_category_2,
    item_category_3,
    item_category_4,
    item_category_5,
    view_promotion,
    select_promotion,
    view_item_list,
    select_item,
    view_item,
    add_to_wishlist,
    add_to_cart,
    remove_from_cart,
    view_cart,
    begin_checkout,
    add_shipping_info,
    add_payment_info,
    item_quantity_purchased,
    item_quantity_refunded,
    item_quantity_added_to_cart,
    item_quantity_removed_from_cart,
    item_purchase_revenue,
    item_refund_revenue,
    item_unique_purchases,
    ifnull(item_purchase_revenue, 0) + ifnull(item_refund_revenue, 0) as item_revenue_net_refund
  from product_prep
  group by all
);