CREATE OR REPLACE TABLE FUNCTION `tom-moretti.nameless_analytics.ec_shopping_stages_open_funnel`(start_date DATE, end_date DATE) AS (
  with base_events as (
    select 
      # USER DATA
      user_date, 
      user_id,
      client_id, 
      user_type, 
      new_user, 
      returning_user,
      user_channel_grouping, 
      user_source,
      user_tld_source, 
      user_campaign, 
      user_campaign_id,
      user_campaign_click_id,
      user_campaign_term,
      user_campaign_content,
      user_device_type, 
      user_country, 
      user_language, 

      # SESSION DATA
      session_date, 
      session_id, 
      session_number, 
      cross_domain_session, 
      session_start_timestamp, 
      session_end_timestamp,
      session_duration_sec,
      new_session,
      returning_session,
      session_channel_grouping, 
      session_source,
      session_tld_source, 
      session_campaign,
      session_campaign_id,
      session_campaign_click_id,
      session_campaign_term,
      session_campaign_content,
      session_device_type, 
      session_browser_name,
      session_country, 
      session_language,
      session_hostname,
      session_landing_page_category, 
      session_landing_page_location, 
      session_landing_page_title, 
      session_exit_page_category, 
      session_exit_page_location, 
      session_exit_page_title,

      # EVENT DATA
      event_date,
      event_name
    from `tom-moretti.nameless_analytics.events`(start_date, end_date, 'session')
  ),

  session_logic as (
    select
      # USER DATA
      user_date, 
      client_id, 
      user_id, 
      user_channel_grouping, 
      user_source, 
      user_tld_source, 
      user_campaign, 
      user_campaign_id,
      user_campaign_click_id,
      user_campaign_term,
      user_campaign_content,
      user_device_type, 
      user_country, 
      user_language, 
      user_type, 
      new_user, 
      returning_user,

      # SESSION DATA
      session_date, 
      session_number, 
      session_id, 
      session_start_timestamp, 
      session_end_timestamp, 
      session_duration_sec, 
      new_session,
      returning_session,
      session_channel_grouping,
      split(session_tld_source, '.')[safe_offset(0)] as session_source_split,
      session_tld_source, 
      session_campaign, 
      session_campaign_id,
      session_campaign_click_id,
      session_campaign_term,
      session_campaign_content,
      cross_domain_session, 
      session_landing_page_category, 
      session_landing_page_location, 
      session_landing_page_title, 
      session_exit_page_category, 
      session_exit_page_location, 
      session_exit_page_title, 
      session_hostname, 
      session_device_type, 
      session_country, 
      session_language, 
      session_browser_name,

      # EVENT DATA
      event_date,
      
      # FUNNEL STEPS
      logical_or(event_name = 'view_item') as has_view_item,
      logical_or(event_name = 'add_to_cart') as has_add_to_cart,
      logical_or(event_name = 'view_cart') as has_view_cart,
      logical_or(event_name = 'begin_checkout') as has_begin_checkout,
      logical_or(event_name = 'add_shipping_info') as has_add_shipping_info,
      logical_or(event_name = 'add_payment_info') as has_add_payment_info,
      logical_or(event_name = 'purchase') as has_purchase
    from base_events
    group by all
  ),

  funnel_logic as (
    select
      # USER DATA
      user_date, 
      client_id, 
      user_id, 
      user_channel_grouping, 
      user_source, 
      user_tld_source, 
      user_campaign, 
      user_campaign_id,
      user_campaign_click_id,
      user_campaign_term,
      user_campaign_content,
      user_device_type, 
      user_country, 
      user_language, 
      user_type, 
      new_user, 
      returning_user,

      # SESSION DATA
      session_date, 
      session_number, 
      session_id, 
      session_start_timestamp, 
      session_end_timestamp, 
      session_duration_sec, 
      new_session,
      returning_session,
      session_channel_grouping, 
      session_source_split, 
      session_tld_source, 
      session_campaign, 
      session_campaign_id,
      session_campaign_click_id,
      session_campaign_term,
      session_campaign_content,
      cross_domain_session, 
      session_landing_page_category, 
      session_landing_page_location, 
      session_landing_page_title, 
      session_exit_page_category, 
      session_exit_page_location, 
      session_exit_page_title, 
      session_hostname, 
      session_device_type, 
      session_country, 
      session_language, 
      session_browser_name,
      event_date,
      
      # OPEN FUNNEL STEPS (0 to 7)
      struct(client_id as cid, session_id as sid, "All" as status) as s0,
      struct(if(has_view_item, client_id, null) as cid, if(has_view_item, session_id, null) as sid, if(has_view_item, 'New funnel entries', null) as status) as s1,
      struct(if(has_add_to_cart, client_id, null) as cid, if(has_add_to_cart, session_id, null) as sid, if(has_add_to_cart, if(has_view_item, 'Continuing funnel entries', 'New funnel entries'), null) as status) as s2,
      struct(if(has_view_cart, client_id, null) as cid, if(has_view_cart, session_id, null) as sid, if(has_view_cart, if(has_add_to_cart, 'Continuing funnel entries', 'New funnel entries'), null) as status) as s3,
      struct(if(has_begin_checkout, client_id, null) as cid, if(has_begin_checkout, session_id, null) as sid, if(has_begin_checkout, if(has_view_cart, 'Continuing funnel entries', 'New funnel entries'), null) as status) as s4,
      struct(if(has_add_shipping_info, client_id, null) as cid, if(has_add_shipping_info, session_id, null) as sid, if(has_add_shipping_info, if(has_begin_checkout, 'Continuing funnel entries', 'New funnel entries'), null) as status) as s5,
      struct(if(has_add_payment_info, client_id, null) as cid, if(has_add_payment_info, session_id, null) as sid, if(has_add_payment_info, if(has_add_shipping_info, 'Continuing funnel entries', 'New funnel entries'), null) as status) as s6,
      struct(if(has_purchase, client_id, null) as cid, if(has_purchase, session_id, null) as sid, if(has_purchase, if(has_add_payment_info, 'Continuing funnel entries', 'New funnel entries'), null) as status) as s7
    from session_logic
  ),

  steps_prep as (
    select
      # USER DATA
      user_date, 
      client_id, 
      user_id, 
      user_channel_grouping, 
      user_source, 
      user_tld_source, 
      user_campaign, 
      user_campaign_id,
      user_campaign_click_id,
      user_campaign_term,
      user_campaign_content,
      user_device_type, 
      user_country, 
      user_language, 
      user_type, 
      new_user, 
      returning_user,

      # SESSION DATA
      session_date, 
      session_number, 
      session_id, 
      session_start_timestamp, 
      session_end_timestamp, 
      session_duration_sec, 
      new_session,
      returning_session,
      session_channel_grouping, 
      session_source_split as session_source, 
      session_tld_source, 
      session_campaign, 
      session_campaign_id,
      session_campaign_click_id,
      session_campaign_term,
      session_campaign_content,
      cross_domain_session, 
      session_landing_page_category, 
      session_landing_page_location, 
      session_landing_page_title, 
      session_exit_page_category, 
      session_exit_page_location, 
      session_exit_page_title, 
      session_hostname, 
      session_device_type, 
      session_country, 
      session_language, 
      session_browser_name,
      event_date,
      
      step_name,
      step_index,
      case when step_name = '7 - Purchase' then null else step_index + 1 end as step_index_next_step_real,
      lead(step_index, 1) over (partition by session_id order by step_index) as step_index_next_step,
      status,
      lead(step_client_id, 1) over (partition by session_id order by step_index) as client_id_next_step_raw,
      lead(step_session_id, 1) over (partition by session_id order by step_index) as session_id_next_step_raw
    from funnel_logic
    unpivot((step_client_id, step_session_id, status) for (step_name, step_index) in (
      (s0.cid, s0.sid, s0.status, "0 - All", 0),
      (s1.cid, s1.sid, s1.status, "1 - View item", 1),
      (s2.cid, s2.sid, s2.status, "2 - Add to cart", 2),
      (s3.cid, s3.sid, s3.status, "3 - View cart", 3),
      (s4.cid, s4.sid, s4.status, "4 - Begin checkout", 4),
      (s5.cid, s5.sid, s5.status, "5 - Add shipping info", 5),
      (s6.cid, s6.sid, s6.status, "6 - Add payment info", 6),
      (s7.cid, s7.sid, s7.status, "7 - Purchase", 7)
    ))
  )

  select 
    # USER DATA
    user_date,
    client_id,
    user_id,
    user_channel_grouping,
    user_source,
    user_tld_source,
    user_campaign,
    user_campaign_id,
    user_campaign_click_id,
    user_campaign_term,
    user_campaign_content,
    user_device_type,
    user_country,
    user_language,
    user_type,
    new_user,
    returning_user,

    # SESSION DATA
    session_date,
    session_number,
    session_id,
    session_start_timestamp,
    session_end_timestamp,
    session_duration_sec,
    new_session,
    returning_session,
    session_channel_grouping,
    session_source,
    session_tld_source,
    session_campaign,
    session_campaign_id,
    session_campaign_click_id,
    session_campaign_term,
    session_campaign_content,
    cross_domain_session,
    session_landing_page_category,
    session_landing_page_location,
    session_landing_page_title,
    session_exit_page_category,
    session_exit_page_location,
    session_exit_page_title,
    session_hostname,
    session_device_type,
    session_country,
    session_language,
    session_browser_name,
    
    # EVENT DATA
    event_date,
    step_name,
    step_index,
    step_index_next_step_real,
    step_index_next_step,
    status,
    case when step_index_next_step_real = step_index_next_step then client_id_next_step_raw end as client_id_next_step,
    case when step_index_next_step_real = step_index_next_step then session_id_next_step_raw end as session_id_next_step
  from steps_prep
  group by all
);