CREATE OR REPLACE TABLE FUNCTION `tom-moretti.nameless_analytics.sessions`(start_date DATE, end_date DATE) AS (
  with base_events as (
    select 
      # USER DATA
      user_date, 
      client_id, 
      user_type, 
      new_user, 
      returning_user,
      user_channel_grouping, 
      user_source,
      user_tld_source, 
      user_campaign, 
      user_campaign_id,
      user_campaign_click_id,
      user_campaign_term,
      user_campaign_content,
      user_device_type, 
      user_country, 
      user_language, 

      # SESSION DATA
      session_date, 
      session_id, 
      session_number, 
      case when session_number = 1 then 1 else 0 end as first_session,
      cross_domain_session, 
      session_start_timestamp, 
      session_end_timestamp,
      session_duration_sec,
      new_session,
      returning_session,
      session_channel_grouping, 
      session_source,
      session_tld_source, 
      session_campaign,
      session_campaign_id,
      session_campaign_click_id,
      session_campaign_term,
      session_campaign_content,
      session_device_type, 
      session_browser_name,
      session_country, 
      session_language,
      session_hostname,
      session_landing_page_category, 
      session_landing_page_location, 
      session_landing_page_title, 
      session_exit_page_category, 
      session_exit_page_location, 
      session_exit_page_title,

      # EVENT DATA
      event_timestamp,
      event_name,
      ecommerce,
      consent_type,
      ad_user_data,
      ad_personalization,
      ad_storage,
      analytics_storage,
      functionality_storage,
      personalization_storage,
      security_storage
    from `tom-moretti.nameless_analytics.events`(start_date, end_date, 'session')
  ),

  session_logic as (
    select
      # USER DATA
      user_date, 
      user_id,
      client_id, 
      user_type, 
      new_user, 
      returning_user,
      user_channel_grouping, 
      split(user_tld_source, '.')[safe_offset(0)] as user_source,
      user_tld_source, 
      user_campaign, 
      user_campaign_click_id,
      user_campaign_term,
      user_campaign_content,
      user_device_type, 
      user_country, 
      user_language, 

      # SESSION DATA
      session_date, 
      session_id, 
      session_number, 
      first_session,
      cross_domain_session, 
      session_start_timestamp, 
      session_duration_sec,
      new_session,
      returning_session,
      session_channel_grouping, 
      split(session_tld_source, '.')[safe_offset(0)] as session_source,
      session_tld_source, 
      session_campaign,
      session_campaign_click_id,
      session_campaign_term,
      session_campaign_content,
      session_device_type, 
      session_browser_name,
      session_country, 
      session_language,
      session_landing_page_category, 
      session_landing_page_location, 
      session_landing_page_title, 
      session_exit_page_category, 
      session_exit_page_location, 
      session_exit_page_title, 
      session_hostname,

      # EVENTS
      countif(event_name = 'page_view') as page_view,

      # ECOMMERCE DATA
      countif(event_name = 'view_item_list') as view_item_list,
      countif(event_name = 'select_item') as select_item,
      countif(event_name = 'view_item') as view_item,
      countif(event_name = 'add_to_wishlist') as add_to_wishlist,
      countif(event_name = 'add_to_cart') as add_to_cart,
      countif(event_name = 'remove_from_cart') as remove_from_cart,
      countif(event_name = 'view_cart') as view_cart,
      countif(event_name = 'begin_checkout') as begin_checkout,
      countif(event_name = 'add_shipping_info') as add_shipping_info,
      countif(event_name = 'add_payment_info') as add_payment_info,
      countif(event_name = 'purchase') as purchase,
      countif(event_name = 'refund') as refund,

      ifnull(sum(case when event_name = 'purchase' then safe_cast(json_value(ecommerce, '$.value') as float64) end), 0) as purchase_revenue,
      ifnull(sum(case when event_name = 'purchase' then safe_cast(json_value(ecommerce, '$.shipping') as float64) end), 0) as purchase_shipping,
      ifnull(sum(case when event_name = 'purchase' then safe_cast(json_value(ecommerce, '$.tax') as float64) end), 0) as purchase_tax,
      ifnull(sum(case when event_name = 'refund' then -safe_cast(json_value(ecommerce, '$.value') as float64) end), 0) as refund_revenue,
      ifnull(sum(case when event_name = 'refund' then -safe_cast(json_value(ecommerce, '$.shipping') as float64) end), 0) as refund_shipping,
      ifnull(sum(case when event_name = 'refund' then -safe_cast(json_value(ecommerce, '$.tax') as float64) end), 0) as refund_tax,

      # CONSENT DATA
      min(event_timestamp) as first_timestamp,
      min(case when consent_type = 'Update' then event_timestamp end) as update_timestamp,
      countif(consent_type = 'Update') > 0 as has_update,

      array_agg(case when consent_type = 'Update' then ad_user_data end ignore nulls order by event_timestamp asc limit 1)[safe_offset(0)] as upd_ad_user_data,
      array_agg(ad_user_data order by event_timestamp asc limit 1)[safe_offset(0)] as def_ad_user_data,

      array_agg(case when consent_type = 'Update' then ad_personalization end ignore nulls order by event_timestamp asc limit 1)[safe_offset(0)] as upd_ad_personalization,
      array_agg(ad_personalization order by event_timestamp asc limit 1)[safe_offset(0)] as def_ad_personalization,

      array_agg(case when consent_type = 'Update' then ad_storage end ignore nulls order by event_timestamp asc limit 1)[safe_offset(0)] as upd_ad_storage,
      array_agg(ad_storage order by event_timestamp asc limit 1)[safe_offset(0)] as def_ad_storage,

      array_agg(case when consent_type = 'Update' then analytics_storage end ignore nulls order by event_timestamp asc limit 1)[safe_offset(0)] as upd_analytics_storage,
      array_agg(analytics_storage order by event_timestamp asc limit 1)[safe_offset(0)] as def_analytics_storage,

      array_agg(case when consent_type = 'Update' then functionality_storage end ignore nulls order by event_timestamp asc limit 1)[safe_offset(0)] as upd_functionality_storage,
      array_agg(functionality_storage order by event_timestamp asc limit 1)[safe_offset(0)] as def_functionality_storage,

      array_agg(case when consent_type = 'Update' then personalization_storage end ignore nulls order by event_timestamp asc limit 1)[safe_offset(0)] as upd_personalization_storage,
      array_agg(personalization_storage order by event_timestamp asc limit 1)[safe_offset(0)] as def_personalization_storage,

      array_agg(case when consent_type = 'Update' then security_storage end ignore nulls order by event_timestamp asc limit 1)[safe_offset(0)] as upd_security_storage,
      array_agg(security_storage order by event_timestamp asc limit 1)[safe_offset(0)] as def_security_storage

    from base_events
    group by all
  ),

  session_prep as (
    select
      # USER DATA
      user_date, 
      user_id,
      client_id, 
      user_type, 
      new_user, 
      returning_user,
      user_channel_grouping, 
      user_source,
      user_tld_source, 
      user_campaign, 
      user_campaign_click_id,
      user_campaign_term,
      user_campaign_content,
      user_device_type, 
      user_country, 
      user_language, 

      # SESSION DATA
      session_date, 
      session_id, 
      session_number,
      first_session,
      cross_domain_session, 
      session_start_timestamp, 
      session_duration_sec,
      new_session,
      returning_session,
      session_channel_grouping, 
      session_source,
      session_tld_source, 
      session_campaign,
      session_campaign_click_id,
      session_campaign_term,
      session_campaign_content,
      session_device_type, 
      session_browser_name,
      session_country, 
      session_language,
      session_landing_page_category, 
      session_landing_page_location, 
      session_landing_page_title, 
      session_exit_page_category, 
      session_exit_page_location, 
      session_exit_page_title, 
      session_hostname,

      # EVENTS
      page_view,

      # ECOMMERCE DATA
      view_item_list,
      select_item,
      view_item,
      add_to_wishlist,
      add_to_cart,
      remove_from_cart,
      view_cart,
      begin_checkout,
      add_shipping_info,
      add_payment_info,
      purchase,
      refund,
      purchase_revenue,
      purchase_shipping,
      purchase_tax,
      refund_revenue,
      refund_shipping,
      refund_tax,

      # CONSENT DATA
      has_update,
      update_timestamp,
      first_timestamp,
      upd_ad_user_data,
      def_ad_user_data,
      upd_ad_personalization,
      def_ad_personalization,
      upd_ad_storage,
      def_ad_storage,
      upd_analytics_storage,
      def_analytics_storage,
      upd_functionality_storage,
      def_functionality_storage,
      upd_personalization_storage,
      def_personalization_storage,
      upd_security_storage,
      def_security_storage,

      case when page_view >= 2 and (session_duration_sec >= 10 or purchase >= 1) then 1 else 0 end as engaged_session,
      if(has_update, update_timestamp, first_timestamp) as consent_timestamp,
      if(has_update, 'Yes', 'No') as consent_expressed,
      if(if(has_update, upd_ad_user_data, def_ad_user_data) = 'Granted', 1, 0) as session_ad_user_data,
      if(if(has_update, upd_ad_personalization, def_ad_personalization) = 'Granted', 1, 0) as session_ad_personalization,
      if(if(has_update, upd_ad_storage, def_ad_storage) = 'Granted', 1, 0) as session_ad_storage,
      if(if(has_update, upd_analytics_storage, def_analytics_storage) = 'Granted', 1, 0) as session_analytics_storage,
      if(if(has_update, upd_functionality_storage, def_functionality_storage) = 'Granted', 1, 0) as session_functionality_storage,
      if(if(has_update, upd_personalization_storage, def_personalization_storage) = 'Granted', 1, 0) as session_personalization_storage,
      if(if(has_update, upd_security_storage, def_security_storage) = 'Granted', 1, 0) as session_security_storage
    from session_logic
  )

  select
    # USER DATA
    user_date, 
    user_id,
    client_id, 
    user_type, 
    new_user, 
    safe_divide(count(distinct new_user), count(distinct client_id)) as `%_new_users`,
    returning_user,
    safe_divide(count(distinct returning_user), count(distinct client_id)) as `%_returning_users`,
    user_channel_grouping, 
    user_source,
    user_tld_source, 
    user_campaign, 
    user_campaign_click_id,
    user_campaign_term,
    user_campaign_content,
    user_device_type, 
    user_country, 
    user_language, 
    safe_divide(sum(purchase), count(distinct client_id)) as user_conversion_rate,
    safe_divide(sum(purchase_revenue), count(distinct client_id)) as user_value,

    # SESSION DATA
    session_date, 
    session_id, 
    session_number, 
    first_session,
    cross_domain_session, 
    session_start_timestamp, 
    session_duration_sec,
    new_session,
    safe_divide(sum(new_session), count(distinct session_id)) as `%_new_sessions`,
    returning_session,
    safe_divide(sum(returning_session), count(distinct session_id)) as `%_returning_sessions`,
    engaged_session,
    safe_divide(sum(engaged_session), count(distinct session_id)) as `%_engaged_sessions`,
    session_channel_grouping, 
    session_source,
    session_tld_source, 
    session_campaign,
    session_campaign_click_id,
    session_campaign_term,
    session_campaign_content,
    session_device_type, 
    session_browser_name,
    session_country, 
    session_language,
    session_landing_page_category, 
    session_landing_page_location, 
    session_landing_page_title, 
    session_exit_page_category, 
    session_exit_page_location, 
    session_exit_page_title, 
    session_hostname,
    safe_divide(sum(purchase), count(distinct session_id)) as session_conversion_rate,
    safe_divide(sum(purchase_revenue), count(distinct session_id)) as session_value,
    safe_divide(count(distinct session_id), count(distinct client_id)) as sessions_per_user,
    safe_divide(sum(page_view), count(distinct session_id)) as page_view_per_session,

    # EVENTS
    page_view,

    # ECOMMERCE DATA
    view_item_list,
    select_item,
    view_item,
    add_to_wishlist,
    add_to_cart,
    remove_from_cart,
    view_cart,
    begin_checkout,
    add_shipping_info,
    add_payment_info,
    purchase,
    refund,
    purchase_revenue,
    purchase_shipping,
    purchase_tax,
    ifnull(safe_divide(sum(purchase_revenue), sum(purchase)), 0) as avg_order_value,
    refund_revenue,
    refund_shipping,
    refund_tax,
    purchase - refund as purchase_net_refund,
    purchase_revenue - refund_revenue as revenue_net_refund,
    purchase_shipping + refund_shipping as shipping_net_refund,
    purchase_tax + refund_tax as tax_net_refund,

    # CONSENT DATA
    consent_timestamp,
    consent_expressed,

    session_ad_user_data,
    safe_divide(sum(session_ad_user_data), count(distinct session_id)) as `%_ad_user_data_accepted`,
    1 - safe_divide(sum(session_ad_user_data), count(distinct session_id)) as `%_ad_user_data_denied`,

    session_ad_personalization,
    safe_divide(sum(session_ad_personalization), count(distinct session_id)) as `%_ad_personalization_accepted`,
    1 - safe_divide(sum(session_ad_personalization), count(distinct session_id)) as `%_ad_personalization_denied`,
    
    session_ad_storage,
    safe_divide(sum(session_ad_storage), count(distinct session_id)) as `%_ad_storage_accepted`,
    1 - safe_divide(sum(session_ad_storage), count(distinct session_id)) as `%_ad_storage_denied`,

    session_analytics_storage,
    safe_divide(sum(session_analytics_storage), count(distinct session_id)) as `%_analytics_storage_accepted`,
    1 - safe_divide(sum(session_analytics_storage), count(distinct session_id)) as `%_analytics_storage_denied`,

    session_functionality_storage,
    safe_divide(sum(session_functionality_storage), count(distinct session_id)) as `%_functionality_storage_accepted`,
    1 - safe_divide(sum(session_functionality_storage), count(distinct session_id)) as `%_functionality_storage_denied`,

    session_personalization_storage,
    session_security_storage,
    safe_divide(sum(session_security_storage), count(distinct session_id)) as `%_security_storage_accepted`,
    1 - safe_divide(sum(session_security_storage), count(distinct session_id)) as `%_security_storage_denied`,

  from session_prep
  group by all
);